### ISSUE TITLE
What about annotations, AOP and Apigee support in the future?

### ISSUE THREAD

**Issue by mnedkov** [LogSentinel/logsentinel-java-client#1]
Hi Bozho,

First, congrats on the start up and best of luck!

A few ideas from my side. Not trying to tell you how to write software, just sharing my experience as I had something similar in a project of mine(it was called ActionHistory).
A) I was using annotations e.g.
@Action("changePassword")
public void changePasswordAction(){}
In this case obviously the annotation will generate a call to your API. That requires less typing and is somehow less intrusive but is also less flexible than API call.
B) I was using AOP. This requires even less typing than annotations because with AspectJ you can intercept the invocation of each method that ends with Action(or each method in certain class/package etc) and log its invocation. As an extreme, you can have a maven plugin that builds on AspectJ that is configured to intercept certain method calls.
C) In another project I was using Apigee(acquired by Google recently). I would recommend it or similar tool for documenting your API. 

So if the project takes off(maybe it did already?) you can consider those suggestions, no need to invest much effort up front i guess =)

Good luck,
Mihail

**Comment by Glamdring** [comment]
Thanks. And absolutely - the annotation/AOP is in the backlog, will soon get to it, I hope.

As for Apigee - I will consider it, but purely for documentation purposes, I'm using swagger - http://app.logsentinel.com/api
